version: '3.3'
   
services:

  runtime:
    image: ware/umi.cms:php-fpm-7.1-alpine
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - "./core:/var/www/html"
      - "./etc/php/php.ini:/usr/local/etc/php/php.ini"

  db:
    image: mysql:5.5
    restart: always
    volumes:
      - data-db:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=${UMI_DB_NAME}
     - MYSQL_USER=${UMI_DB_USERNAME}
     - MYSQL_PASSWORD=${UMI_DB_PASSWORD}

  web:
    image: nginx
    restart: always
    depends_on:
      - runtime
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./core:/var/www/html"
      - "./app:/var/www/html/templates/app"
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./etc/certs:/etc/nginx/certs"

volumes:
   data-db:
     driver: local
