#!/usr/bin/env bash

TAG=$(echo $IMAGE_NAME| cut -d':' -f 2)

echo "------ HOOK START - POST PUSH -------"

if [ "$TAG" == "7.1" ]; then
  docker tag $IMAGE_NAME $DOCKER_REPO:latest
  docker push $DOCKER_REPO:latest
fi

echo "------ HOOK END - POST PUSH -------"
