name: Build docker image
on:
  workflow_dispatch:
    inputs:
      IMAGE_NAME:
        type: string
        required: true
        default: 'php-fpm-7.4-alpine'
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: image/Dockerfile-${{ github.event.inputs.IMAGE_NAME }}
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.event.inputs.IMAGE_NAME }}
